### ISSUE TITLE
BUG: Closing camera causes a native error - promise was null in onActivityResult

### ISSUE THREAD

**Issue by Abhisflyingsoon** [WebsiteBeaver/react-native-document-scanner-plugin#39]
Phone Model: Galaxy A8
OS Version: Android 9

Steps to produce error: Open camera -> Tap "Back"- Button on device -> Crash/Error (see below) 

Error log from Android Studio: 
E/RNDocumentPicker: promise was null in onActivityResult

 E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.bridge.UnexpectedNativeTypeException: Value for message cannot be cast from ReadableNativeMap to String
        at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:140)
        at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:128)
        at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:162)
        at com.facebook.react.modules.dialog.DialogModule.showAlert(DialogModule.java:195)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)

E/unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.UnexpectedNativeTypeException: Value for message cannot be cast from ReadableNativeMap to String
        at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:140)
        at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:128)
        at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:162)
        at com.facebook.react.modules.dialog.DialogModule.showAlert(DialogModule.java:195)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)

Haven't tried it on other Android versions and iOS yet. 
When I log out the status, it prints "cancel" and then it crashes.

**Comment by Abhisflyingsoon** [comment]
Seems like the error appears because of the promise being null/undefined @ line 90 in DocumentScannerModule.java. I hotfixed it by removing the line: 
// when user cancels document scan
response.putString("status", "cancel");
//promise.resolve(response); --> **commented this line**
return null;

**Comment by dmarcs** [comment]
hi @Abhisflyingsoon the error you posted comes from RNDocumentPicker, not this plugin
