### ISSUE TITLE
color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by shahawi** [WebsiteBeaver/react-native-document-scanner-plugin#78]
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1187240990, result=-1, data=null} to activity {com.*/com.websitebeaver.documentscanner.DocumentScannerActivity}: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.0) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
 
 Hi,
 
 This error is driving me crazy, It causes the app to crash, It shows there is an error in color.cpp related to (-215:Assertion failed) !_src.empty() in function 'cvtColor'
 
 
 I am using android 11
 
 The camera opens normally and takes the picture, The crash happens when clicking the right button.
 
 I am using the library like this
 
  const {scannedImages} = await DocumentScanner.scanDocument();
        if (scannedImages.length > 0) {
          const base64Images = [];
          for (const image of scannedImages) {
            const base64Image = await RNFS.readFile(image, 'base64');
            base64Images.push(base64Image);
          }
          // setScannedImages(base64Images);
          return base64Images; // Return the scanned images
          
          And I followed the setup instructions written here in this project

**Comment by shahawi** [comment]
This error does not happen in the emulator I think it is related to how the phone handles image paths

**Comment by dmarcs** [comment]
try to create a new React Native project, install only this plugin, and see if it happens.

**Comment by shahawi** [comment]
Thank you for your quick response 
The issue is with the 
https://github.com/WebsiteBeaver/android-document-scanner
repository

Can you check pull request #30 in that repository I tried to fix it but I am unable to test
@dmarcs

**Comment by alexglazkov9** [comment]
@dmarcs I finally got my hands on one of the Motorola devices that seem to be affected by this issue. I discovered some issues on android.

1. Below is a log from the demo of `android-document-scanner`. What happens is I run the demo and without any interactions it just crashes within 1-3 minutes with the following log(i've added logs to `ImageUtil.kt` first two lines):
```
2023-05-15 16:28:45.020 27225-27225/com.websitebeaver.documentscanner.demo D/DEBUG: /storage/emulated/0/Android/data/com.websitebeaver.documentscanner.demo/files/Pictures/DOCUMENT_SCAN_0_20230515_162644953650719.jpg
2023-05-15 16:28:45.020 27225-27225/com.websitebeaver.documentscanner.demo D/DEBUG: File exists: true
2023-05-15 16:28:45.022 27225-27225/com.websitebeaver.documentscanner.demo E/cv::error(): OpenCV(4.1.0) Error: Assertion failed (!_src.empty()) in cvtColor, file /build/master_pack-android/opencv/modules/imgproc/src/color.cpp, line 182
2023-05-15 16:28:45.026 27225-27225/com.websitebeaver.documentscanner.demo E/org.opencv.imgproc: imgproc::cvtColor_11() caught cv::Exception: OpenCV(4.1.0) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
2023-05-15 16:28:45.027 27225-27225/com.websitebeaver.documentscanner.demo D/AndroidRuntime: Shutting down VM
2023-05-15 16:28:45.028 27225-27225/com.websitebeaver.documentscanner.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.websitebeaver.documentscanner.demo, PID: 27225
    java.lang.RuntimeException: Unable to resume activity {com.websitebeaver.documentscanner.demo/com.websitebeaver.documentscanner.DocumentScannerActivity}: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.0) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
    ]
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3121)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.0) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
    ]
        at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
        at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:2309)
        at com.websitebeaver.documentscanner.utils.ImageUtil.getImageFromFilePath(ImageUtil.kt:41)
        at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:88)
        at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:75)
        at com.websitebeaver.documentscanner.utils.CameraUtil.startForResult$lambda-0(CameraUtil.kt:41)
        at com.websitebeaver.documentscanner.utils.CameraUtil.$r8$lambda$QtmUm3JcXlX2aa1YkJnrPoMUzS8(CameraUtil.kt)
        at com.websitebeaver.documentscanner.utils.CameraUtil$$ExternalSyntheticLambda0.onActivityResult(D8$$SyntheticClass)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
        at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
        at android.app.Fragment.performStart(Fragment.java:2244)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1002)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1960)
        at android.app.FragmentController.dispatchStart(FragmentController.java:163)
        at android.app.Activity.performStart(Activity.java:6267)
        at android.app.Activity.performRestart(Activity.java:6307)
        at android.app.Activity.performResume(Activity.java:6312)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
        	... 8 more
```

2. When I actually try to capture the image, i get a black screen during the cropping step, however, i can see the cropped image after it was cropped, with the following log:
```
2023-05-15 16:31:38.098 27607-27607/com.websitebeaver.documentscanner.demo D/DEBUG: /storage/emulated/0/Android/data/com.websitebeaver.documentscanner.demo/files/Pictures/DOCUMENT_SCAN_0_20230515_163133-1312137198.jpg
2023-05-15 16:31:38.098 27607-27607/com.websitebeaver.documentscanner.demo D/DEBUG: File exists: true
2023-05-15 16:31:39.754 27607-27744/com.websitebeaver.documentscanner.demo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
2023-05-15 16:31:39.810 27607-27744/com.websitebeaver.documentscanner.demo I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I3193f6e94a)
    OpenGL ES Shader Compiler Version: E031.28.00.02
    Build Date: 10/09/15 Fri
    Local Branch: mybranch15039904
    Remote Branch: quic/LA.BF.1.1.3_rb1.2
    Local Patches: NONE
    Reconstruct Branch: NOTHING
2023-05-15 16:31:39.817 27607-27744/com.websitebeaver.documentscanner.demo I/OpenGLRenderer: Initialized EGL, version 1.4
2023-05-15 16:31:39.847 27607-27744/com.websitebeaver.documentscanner.demo W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:31:39.861 27607-27744/com.websitebeaver.documentscanner.demo W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:31:39.861 27607-27744/com.websitebeaver.documentscanner.demo W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:31:40.161 27607-27744/com.websitebeaver.documentscanner.demo W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:31:40.162 27607-27744/com.websitebeaver.documentscanner.demo W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:31:40.162 27607-27744/com.websitebeaver.documentscanner.demo W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
```
3. Finally when I run example from `react-native-document-scanner-plugin` on the same device, i get the similar behaviour to # 2(so take an image, image is visible, go to cropper, black screen), but it ultimately crashes after you crop it, with the following log:
```
2023-05-15 16:45:06.775 29203-29253/com.example.reactnativedocumentscanner W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:45:06.775 29203-29253/com.example.reactnativedocumentscanner W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:45:06.775 29203-29253/com.example.reactnativedocumentscanner W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:45:07.091 29203-29253/com.example.reactnativedocumentscanner W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:45:07.092 29203-29253/com.example.reactnativedocumentscanner W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:45:07.093 29203-29253/com.example.reactnativedocumentscanner W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:45:08.230 29203-29253/com.example.reactnativedocumentscanner W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:45:08.246 29203-29253/com.example.reactnativedocumentscanner W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:45:08.263 29203-29253/com.example.reactnativedocumentscanner W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:45:08.280 29203-29253/com.example.reactnativedocumentscanner W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)
2023-05-15 16:45:09.975 29203-29203/com.example.reactnativedocumentscanner I/Choreographer: Skipped 100 frames!  The application may be doing too much work on its main thread.
2023-05-15 16:45:09.983 29203-29203/com.example.reactnativedocumentscanner I/art: Rejecting re-init on previously-failed class java.lang.Class<com.reactnativedocumentscanner.-$$Lambda$DocumentScannerModule$Q4ouggW8dLKZVyX_qanZKL8Mvdo>
2023-05-15 16:45:09.995 29203-29203/com.example.reactnativedocumentscanner D/AndroidRuntime: Shutting down VM
2023-05-15 16:45:10.012 29203-29203/com.example.reactnativedocumentscanner E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.reactnativedocumentscanner, PID: 29203
    java.lang.NoClassDefFoundError: com.reactnativedocumentscanner.-$$Lambda$DocumentScannerModule$Q4ouggW8dLKZVyX_qanZKL8Mvdo
        at com.reactnativedocumentscanner.DocumentScannerModule.lambda$scanDocument$1(DocumentScannerModule.java:70)
        at com.reactnativedocumentscanner.-$$Lambda$DocumentScannerModule$VopbdLiWknFSlGfEZAKQOPDvLEo.invoke(lambda)
        at com.websitebeaver.documentscanner.DocumentScanner.handleDocumentScanIntentResult(DocumentScanner.kt:119)
        at com.reactnativedocumentscanner.DocumentScannerModule$1.onActivityResult(DocumentScannerModule.java:41)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
        at android.app.Activity.dispatchActivityResult(Activity.java:6442)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
        at android.app.ActivityThread.-wrap16(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
2023-05-15 16:45:12.755 29203-29203/com.example.reactnativedocumentscanner I/Process: Sending signal. PID: 29203 SIG: 9
```
Related to https://github.com/WebsiteBeaver/android-document-scanner/issues/29

**Comment by dmarcs** [comment]
@alexglazkov9 I might need to add a check to prevent `Bitmap too large to be uploaded into a texture (2340x4160, max=4096x4096)`, but I don't think this is what causes `color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`.

It seems like there are 2 different issues here.
1. You get a black screen during the crop step
2. OpenCV isn't able to read the image

We need to figure out why OpenCV can't read the image.

In the OpenCV docs it says
> If the image cannot be read (because of missing file, improper permissions, unsupported or invalid format), the function returns an empty matrix ( Mat::data==NULL )

You verified that the file isn't missing. It's possible that you don't have permission to read the file.

Are you able to consistently reproduce the color.cpp bug? If you are, can you try to manually read an image that has smaller dimensions?

https://github.com/WebsiteBeaver/android-document-scanner/blob/master/documentscanner/src/main/java/com/websitebeaver/documentscanner/utils/ImageUtil.kt
`val image: Mat = Imgcodecs.imread(filePath)`

**Comment by shahawi** [comment]
I have made a pull request here
https://github.com/WebsiteBeaver/android-document-scanner/pull/32

bare in mind my changes require minimum android sdk 29

Maybe someone can splice old and new codes together

**Comment by dmarcs** [comment]
Fixed in https://github.com/WebsiteBeaver/android-document-scanner/pull/33 by making sure image isn't empty before calling `cvtColor`. If it is try reading image without OpenCV.
