### ISSUE TITLE
Crash when trying to resume activity

### ISSUE THREAD

**Issue by ggherardi** [WebsiteBeaver/react-native-document-scanner-plugin#99]
Hi, I'm trying to use this package, but I'm encountering this issue.
On Android it happens very often (I didn't test it on iOS yet): I open the camera with DocumentScanner, take a photo, and the app crashes even before letting me crop the image. This is the error and call stack:

FATAL EXCEPTION: main
                                                                                                    Process: com.tlm, PID: 32163
                                                                                                    java.lang.RuntimeException: Unable to resume activity {com.tlm/com.websitebeaver.documentscanner.DocumentScannerActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1622664263, result=-1, data=null} to activity {com.tlm/com.websitebeaver.documentscanner.DocumentScannerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4206)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4238)
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7397)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
                                                                                                    Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1622664263, result=-1, data=null} to activity {com.tlm/com.websitebeaver.documentscanner.DocumentScannerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:4846)
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4193)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4238) 
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:214) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7397) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                                    	at com.websitebeaver.documentscanner.utils.ImageUtil.getImageMatrixFromFilePath(ImageUtil.kt:68)
                                                                                                    	at com.websitebeaver.documentscanner.utils.ImageUtil.getImageFromFilePath(ImageUtil.kt:86)
                                                                                                    	at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:88)
                                                                                                    	at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:75)
                                                                                                    	at com.websitebeaver.documentscanner.utils.CameraUtil.startForResult$lambda-0(CameraUtil.kt:41)
                                                                                                    	at com.websitebeaver.documentscanner.utils.CameraUtil.$r8$lambda$QtmUm3JcXlX2aa1YkJnrPoMUzS8(Unknown Source:0)
                                                                                                    	at com.websitebeaver.documentscanner.utils.CameraUtil$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
                                                                                                    	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:647)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:4839)
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4193) 
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4238) 
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:214) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7397) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 

Please advice me, I'm kinda new to React Native and app development in general, and I feel it would a serious chore to write a new library.

**Comment by dmarcs** [comment]
I think you're right about the empty image causing the Bitmap.getWidth() error message. I'm just not sure why an empty image gets saved.

**Comment by ggherardi** [comment]
I will try to test with more devices to see if it's an issue with the current phone I'm using. I'm guessing no one else encountered this issue before.

**Comment by shahawi** [comment]
I have the same issue, For me it happens when the device ahs low memory.

I don't know if checking device for low memory warnings would help or not

**Comment by shahawi** [comment]
Maybe this is an idea at imagutils.kt 

    try {
        imageBitmap = BitmapFactory.decodeFile(filePath)
    } catch (e: Exception) {
        Log.e("ImageUtil", "Error decoding image: ${e.message}")
    }

    if (imageBitmap == null) {
       //maybe do something here
    }

**Comment by fellipesnoww** [comment]
Same issue here :/

**Comment by sanduluca** [comment]
We got same issue on Android 10,11,12,13,14
![image](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/assets/56228534/06af9309-7f14-41aa-9655-372115b829f7)
![image](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/assets/56228534/d8f90043-66cf-4e99-85fc-10571690730a)
![image](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/assets/56228534/e22e18f4-9117-4ff3-9789-8df4decb34c4)
![image](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/assets/56228534/81539c81-06ea-46e7-ad49-0ed2537e71f9)
![image](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/assets/56228534/2efdabf6-3d4b-4076-b180-364dc492b1fd)
![image](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/assets/56228534/39f5710f-fd3e-47f7-b10e-2d77b0843225)


```
# Crashlytics - Stack trace
# Application: com.apptest
# Platform: android
# Version: 0.7.9 
# Date: Thu Mar 14 2024 11:04:59 GMT+0200 (Eastern European Standard Time)

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.apptest/com.websitebeaver.documentscanner.DocumentScannerActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1895268537, result=-1, data=null} to activity {com.apptest/com.websitebeaver.documentscanner.DocumentScannerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5049)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5082)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8294)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1895268537, result=-1, data=null} to activity {com.apptest/com.websitebeaver.documentscanner.DocumentScannerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5599)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5035)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5082)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8294)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at com.websitebeaver.documentscanner.utils.ImageUtil.getImageMatrixFromFilePath(ImageUtil.kt:68)
       at com.websitebeaver.documentscanner.utils.ImageUtil.getImageFromFilePath(ImageUtil.kt:86)
       at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:88)
       at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:75)
       at com.websitebeaver.documentscanner.utils.CameraUtil.startForResult$lambda-0(CameraUtil.kt:41)
       at com.websitebeaver.documentscanner.utils.CameraUtil.$r8$lambda$QtmUm3JcXlX2aa1YkJnrPoMUzS8()
       at com.websitebeaver.documentscanner.utils.CameraUtil$$ExternalSyntheticLambda0.onActivityResult(:4)
       at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
       at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
       at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:793)
       at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
       at android.app.Activity.dispatchActivityResult(Activity.java:8923)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5592)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5035)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5082)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8294)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

```
